/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbfinalproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author chris
 */
public class CustomerOrdersGUI extends javax.swing.JFrame {
    final String database_URL = "jdbc:derby://localhost:1527/dbCoffeeStoreData";
    
    /**
     * Creates new form CustomerOrdersGUI
     */
    public CustomerOrdersGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrders = new javax.swing.JTextArea();
        DisplayIDBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        custIDTxt = new javax.swing.JTextField();
        DisplayAllBtn = new javax.swing.JButton();
        jlblStatus = new javax.swing.JLabel();
        mainGUIBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer Orders");

        jTextAreaOrders.setColumns(20);
        jTextAreaOrders.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOrders);

        DisplayIDBtn.setText("Display by ID");
        DisplayIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayIDBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer ID:");

        DisplayAllBtn.setText("Display All");
        DisplayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAllBtnActionPerformed(evt);
            }
        });

        jlblStatus.setText(" ");

        mainGUIBtn.setText("Main Screen Page");
        mainGUIBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainGUIBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DisplayIDBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DisplayAllBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jlblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainGUIBtn)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(custIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayIDBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayAllBtn)
                .addGap(26, 26, 26)
                .addComponent(mainGUIBtn)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayIDBtnActionPerformed
        // TODO add your handling code here:
        try(
            Connection connection = DriverManager.getConnection(database_URL, "me", "me");
            Statement statement = connection.createStatement();
            ){
        
        int id = Integer.parseInt(custIDTxt.getText());
        //PreparedStatement stmt = connection.prepareStatement("SELECT * FROM INVENTORY WHERE ID = (?)");
        //stmt.setInt(1, id);
        //    int a = stmt.executeUpdate();
        //    if (a>0){
        //        jlblStatus.setText("Row selected");
        //    }
        jTextAreaOrders.setText("");
        ResultSet resultSet = statement.executeQuery(String.format("SELECT FIRST_NAME, LAST_NAME, COFFEE_ID, NUMBER_ORDERED, TOTAL FROM CUSTOMER JOIN ORDERS ON CUSTOMER_NUMBER = CUSTOMER_ID WHERE CUSTOMER_NUMBER = %d "
                + "ORDER BY FIRST_NAME", id));
        ResultSetMetaData metaData = resultSet.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            
            jTextAreaOrders.append(String.format("Customer Orders %n%n"));
            
            for(int i = 1; i <= numberOfColumns; i++){
                jTextAreaOrders.append(String.format("%-8s\t", metaData.getColumnName(i)));
            }
            jTextAreaOrders.append(String.format("%n"));
            while(resultSet.next()){
                for(int i = 1; i <= numberOfColumns; i++){
                    jTextAreaOrders.append(String.format("%-8s\t", resultSet.getObject(i)));
                }
                jTextAreaOrders.append(String.format("%n"));
        }
        }catch(Exception e){
            e.printStackTrace();
            jlblStatus.setText("Row not found");
            
        }
    }//GEN-LAST:event_DisplayIDBtnActionPerformed

    private void DisplayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAllBtnActionPerformed
        // TODO add your handling code here:
        String displayStatement = "SELECT FIRST_NAME, LAST_NAME, COFFEE_ID, NUMBER_ORDERED, TOTAL FROM CUSTOMER JOIN ORDERS ON CUSTOMER_NUMBER = CUSTOMER_ID ORDER BY LAST_NAME";
        try(Connection connection = DriverManager.getConnection(database_URL, "me", "me");
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(displayStatement))
        {
            jTextAreaOrders.setText("");
            ResultSetMetaData metaData = resultSet.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            
            jTextAreaOrders.append(String.format("Customer Orders %n%n"));
            
            for(int i = 1; i <= numberOfColumns; i++){
                jTextAreaOrders.append(String.format("%-8s\t", metaData.getColumnName(i)));
            }
            jTextAreaOrders.append(String.format("%n"));
            while(resultSet.next()){
                for(int i = 1; i <= numberOfColumns; i++){
                    jTextAreaOrders.append(String.format("%-8s\t", resultSet.getObject(i)));
                }
                jTextAreaOrders.append(String.format("%n"));
            }
        }
        
        catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DisplayAllBtnActionPerformed

    private void mainGUIBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainGUIBtnActionPerformed
        // TODO add your handling code here:
        MainScreenGUI main = new MainScreenGUI();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_mainGUIBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrdersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerOrdersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayAllBtn;
    private javax.swing.JButton DisplayIDBtn;
    private javax.swing.JTextField custIDTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOrders;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JButton mainGUIBtn;
    // End of variables declaration//GEN-END:variables
}
